### ISSUE TITLE
Containers and symbols... and printing them.

### ISSUE THREAD

**Issue by jebotz** [vrurg/vrurg.github.io#1]
In your blog post your wrote:
> my $a = [1, 2];
> say $a;           # $[1, 2]

When I try this with rakudo 2020.06 it does not print the '$'.  Also later on, where you say that printing `@a` yields `[$[1, 2],]`, I just get `[[1,2]]`.  Perhaps there is some add-on to plain rakudo that makes it print the way you show it?  Edit: given what I discovered for issue #2, perhaps something that overrides `.gist`..?

**Comment by vrurg** [comment]
Thank you! This piece I was writing while prepared my macbook for a repair and had no means to test the examples. Apparently, forgot about `.raku` method and to check the example later.

Thank you! 

Fixed with a726793f5aa1e4a5e4e8b87d9dab2393ced19dec

**Comment by vrurg** [comment]
Ah, and with regard to [$[...],] case – there is no way to get `$` in front of an array element because they're all containerized by default and thus it makes no sense to explicitly express this.
