### ISSUE TITLE
Containers and Symbols... say vs print

### ISSUE THREAD

**Issue by jebotz** [vrurg/vrurg.github.io#2]
In your blog post you wrote:
> say is like print but always appends a new line at the end

Sort of... but not really.  Aside from the final newline, `say` is different because it prints the `.gist` of objects, which I understand to be a serialized version of the object, whereas `print` prints the `.Str` of objects, i.e. a stringified version.

**Comment by vrurg** [comment]
Let me correct you a bit. `gist` is supposed to print a human-readable version, `Str` – machine readable, `raku` is the closest one to serialization as it produces something we can feed back to the compiler.

Anyway, it's a good point! Though `gist`/`Str` is not relevant to the subject and I better skip it for simplicity. But I added a warning about simplifications in the introductory chapter and tried to make the note `say` and `print` similarity less strict. Hope it works this way. Feel free to re-open the case if you think it's still confusing.

Thank you!
